// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX-Kobk2zncwrJnj3BsA3k4jOXVUAprq8',
    appId: '1:891305690496:web:92a81279e8c975541eed65',
    messagingSenderId: '891305690496',
    projectId: 'e-commerce-d7b46',
    authDomain: 'e-commerce-d7b46.firebaseapp.com',
    storageBucket: 'e-commerce-d7b46.appspot.com',
    measurementId: 'G-M58Q6KFW24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWAwllGD1CApisTKj8IlATBekHRkyhaFU',
    appId: '1:891305690496:android:990cc09cae88c7b51eed65',
    messagingSenderId: '891305690496',
    projectId: 'e-commerce-d7b46',
    storageBucket: 'e-commerce-d7b46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg_C2PreA_AlUdQsbi8DdGY7S1bqR39oY',
    appId: '1:891305690496:ios:b35a9144d64c2f111eed65',
    messagingSenderId: '891305690496',
    projectId: 'e-commerce-d7b46',
    storageBucket: 'e-commerce-d7b46.appspot.com',
    iosClientId: '891305690496-o53hghbs9v7h0fljpk508aptb0m20tg3.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg_C2PreA_AlUdQsbi8DdGY7S1bqR39oY',
    appId: '1:891305690496:ios:b35a9144d64c2f111eed65',
    messagingSenderId: '891305690496',
    projectId: 'e-commerce-d7b46',
    storageBucket: 'e-commerce-d7b46.appspot.com',
    iosClientId: '891305690496-o53hghbs9v7h0fljpk508aptb0m20tg3.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
